CREATE DATABASE Olympics_Fanzone_Trell;

CREATE TABLE SchedulePage(
    ID SERIAL PRIMARY KEY,
    _EVENT VARCHAR(255),
    STARTDATE VARCHAR(255), 
    ENDDATE VARCHAR(255),
    COUNTRY VARCHAR(255)
);